// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjykodoophmginbquluv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqeWtvZG9vcGhtZ2luYnF1bHV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTE2NzgsImV4cCI6MjA2NTk2NzY3OH0.EBbnjhNHJhJGXIlx5CQ8wUbBAyeFYXjIOHZ0z_LhB7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);